# Copyright (c) 2025 GenOrca. All Rights Reserved.
#
# AUTO-GENERATED by generate_catalog.py — do not edit by hand.
# Regenerate: python generate_catalog.py

CATALOG = {
    'actor': {
        'delete_by_label': {
            'params': 'actor_label',
            'doc': 'Deletes an actor with the specified name from the current level.',
        },
        'duplicate_selected': {
            'params': 'offset',
            'doc': 'Duplicates all selected actors in the editor and applies a position offset to each duplicate.',
        },
        'get_all_details': {
            'params': '',
            'doc': 'Lists all actors in the current level with detailed information including',
        },
        'get_in_view_frustum': {
            'params': '',
            'doc': "Retrieves a list of actors that are potentially visible within the active editor viewport's frustum.",
        },
        'get_property': {
            'params': 'actor_label, property_name',
            'doc': 'Gets a property value from an actor using get_editor_property().',
        },
        'invert_selection': {
            'params': '',
            'doc': 'Inverts the selection of actors in the current level.',
        },
        'line_trace': {
            'params': "ray_start, ray_end, trace_channel='Visibility', actors_to_ignore_labels, trace_complex=True",
            'doc': 'Performs a line trace (raycast) and returns hit information without spawning anything.',
        },
        'list_all_with_locations': {
            'params': '',
            'doc': 'Lists all actors in the current level along with their world locations.',
        },
        'select_all': {
            'params': '',
            'doc': 'Selects all actors in the current level.',
        },
        'set_location': {
            'params': 'actor_label, location',
            'doc': '',
        },
        'set_property': {
            'params': 'actor_label, property_name, value',
            'doc': 'Sets a property value on an actor using set_editor_property().',
        },
        'set_rotation': {
            'params': 'actor_label, rotation',
            'doc': '',
        },
        'set_scale': {
            'params': 'actor_label, scale',
            'doc': '',
        },
        'set_transform': {
            'params': 'actor_label, location, rotation, scale',
            'doc': 'Sets the transform (location, rotation, scale) of a specified actor.',
        },
        'spawn_from_class': {
            'params': 'class_path, location, rotation',
            'doc': 'Spawns an actor from the specified class path at the given location and rotation',
        },
        'spawn_from_object': {
            'params': 'asset_path, location',
            'doc': 'Spawns an actor from the specified asset path at the given location.',
        },
        'spawn_on_surface_raycast': {
            'params': "asset_or_class_path, ray_start, ray_end, is_class_path=True, desired_rotation, location_offset, trace_channel='Visibility', actors_to_ignore_labels",
            'doc': '',
        },
    },
    'asset': {
        'find_by_query': {
            'params': 'name, asset_type',
            'doc': "Returns a JSON list of asset paths under '/Game' matching the given query dict.",
        },
        'get_static_mesh_details': {
            'params': 'asset_path',
            'doc': 'Retrieves the bounding box and dimensions of a static mesh asset.',
        },
    },
    'behavior_tree': {
        'add_blackboard_key': {
            'params': 'asset_path, key_name, key_type, instance_synced=False',
            'doc': 'Adds a new key to a Blackboard asset.',
        },
        'build_behavior_tree': {
            'params': 'asset_path, tree_structure',
            'doc': 'Builds a complete Behavior Tree from a JSON structure.',
        },
        'create_behavior_tree': {
            'params': 'asset_path, blackboard_path',
            'doc': 'Creates a new empty Behavior Tree asset.',
        },
        'create_blackboard': {
            'params': 'asset_path, parent_path',
            'doc': 'Creates a new Blackboard Data asset.',
        },
        'get_behavior_tree_structure': {
            'params': 'asset_path',
            'doc': 'Returns the full tree structure of a Behavior Tree asset as JSON.',
        },
        'get_blackboard_data': {
            'params': 'asset_path',
            'doc': 'Reads all keys from a Blackboard asset.',
        },
        'get_bt_node_details': {
            'params': 'asset_path, node_name',
            'doc': 'Retrieves detailed properties of a specific node in a Behavior Tree.',
        },
        'get_selected_bt_nodes': {
            'params': '',
            'doc': 'Returns details of selected nodes in the currently open BT editor.',
        },
        'list_behavior_trees': {
            'params': '',
            'doc': 'Lists all Behavior Tree assets under /Game.',
        },
        'list_bt_node_classes': {
            'params': '',
            'doc': 'Lists all available BT node classes (composites, tasks, decorators, services).',
        },
        'remove_blackboard_key': {
            'params': 'asset_path, key_name',
            'doc': 'Removes a key from a Blackboard asset.',
        },
        'set_blackboard_to_behavior_tree': {
            'params': 'bt_path, bb_path',
            'doc': 'Links a Blackboard asset to a Behavior Tree.',
        },
    },
    'blueprint': {
        'add_blueprint_node': {
            'params': "asset_path, graph_name='EventGraph', node_json",
            'doc': 'Adds a single node to a Blueprint graph.',
        },
        'add_component_to_blueprint': {
            'params': "asset_path, component_class_path, component_name, location_x=0.0, location_y=0.0, location_z=0.0, rotation_pitch=0.0, rotation_yaw=0.0, rotation_roll=0.0, parent_component_name=''",
            'doc': "Adds a component to a Blueprint's SCS.",
        },
        'auto_layout_graph': {
            'params': "asset_path, graph_name='EventGraph', x_step=380.0, y_step=200.0",
            'doc': 'Auto-lays out all nodes in a Blueprint graph using DAG topological sort.',
        },
        'build_blueprint_graph': {
            'params': "asset_path, graph_name='EventGraph', graph_structure",
            'doc': 'Builds a Blueprint graph from JSON adjacency list.',
        },
        'compile_blueprint': {
            'params': 'asset_path',
            'doc': 'Compiles a Blueprint and returns the result.',
        },
        'connect_blueprint_pins': {
            'params': "asset_path, graph_name='EventGraph', source_node, source_pin, target_node, target_pin",
            'doc': 'Connects two pins in a Blueprint graph.',
        },
        'get_blueprint_graph_info': {
            'params': "asset_path, graph_name='EventGraph'",
            'doc': 'Returns the full graph info for a Blueprint graph.',
        },
        'get_selected_bp_node_infos': {
            'params': '',
            'doc': 'Returns compact blueprint node info optimized for LLM token efficiency.',
        },
        'get_selected_bp_nodes': {
            'params': '',
            'doc': 'Returns information about currently selected blueprint nodes in the editor.',
        },
        'list_blueprint_components': {
            'params': 'asset_path',
            'doc': 'Lists all SCS components on a Blueprint.',
        },
        'list_blueprint_variables': {
            'params': 'asset_path',
            'doc': 'Lists all variables defined in a Blueprint.',
        },
        'list_callable_functions': {
            'params': "asset_path, filter=''",
            'doc': 'Lists callable functions available in a Blueprint context.',
        },
        'remove_blueprint_node': {
            'params': "asset_path, graph_name='EventGraph', node_name",
            'doc': 'Removes a node from a Blueprint graph.',
        },
        'remove_component_from_blueprint': {
            'params': 'asset_path, component_name',
            'doc': "Removes a component by variable name from a Blueprint's SCS.",
        },
        'set_blueprint_node_position': {
            'params': "asset_path, graph_name='EventGraph', node_name, pos_x=0.0, pos_y=0.0",
            'doc': 'Sets the canvas position of a node in a Blueprint graph.',
        },
        'set_component_property': {
            'params': 'asset_path, component_name, property_name, value',
            'doc': "Sets a property on a component template in a Blueprint's SCS.",
        },
    },
    'editor': {
        'get_selected_assets': {
            'params': '',
            'doc': 'Gets the set of currently selected assets.',
        },
        'replace_mesh_on_selected': {
            'params': 'mesh_to_be_replaced_path, new_mesh_path',
            'doc': "Replaces static meshes on components of selected actors using Unreal's batch API if available.",
        },
        'replace_mesh_on_specified': {
            'params': 'actor_paths, mesh_to_be_replaced_path, new_mesh_path',
            'doc': "Replaces static meshes on components of specified actors using Unreal's batch API if available.",
        },
        'replace_mtl_on_selected': {
            'params': 'material_to_be_replaced_path, new_material_path',
            'doc': '',
        },
        'replace_mtl_on_specified': {
            'params': 'actor_paths, material_to_be_replaced_path, new_material_path',
            'doc': '',
        },
        'replace_selected_with_bp': {
            'params': 'blueprint_asset_path',
            'doc': "Replaces the currently selected actors with new actors spawned from a specified Blueprint asset path using Unreal's official API.",
        },
    },
    'game': {
        'add_input_action': {
            'params': "asset_path, value_type='Bool'",
            'doc': 'Creates a new Enhanced Input Action asset.',
        },
        'add_input_mapping': {
            'params': 'mapping_context_path, action_path, key_name',
            'doc': 'Creates/updates an InputMappingContext with a key-to-action mapping.',
        },
        'set_game_mode': {
            'params': 'game_mode_class_path',
            'doc': "Sets the GameMode Override on the current level's World Settings.",
        },
    },
    'level': {
        'create_level': {
            'params': 'level_path',
            'doc': 'Creates a new empty level and saves it at the given content-browser path.',
        },
        'list_level_actors': {
            'params': 'class_filter',
            'doc': 'Lists all actors in the current level.',
        },
        'load_level': {
            'params': 'level_path',
            'doc': 'Opens (loads) an existing level in the editor.',
        },
        'set_world_settings': {
            'params': 'gravity, time_dilation',
            'doc': 'Modifies WorldSettings of the current level.',
        },
    },
    'material': {
        'connect_expressions': {
            'params': 'material_path, from_expression_identifier, from_output_name, to_expression_identifier, to_input_name, from_expression_class_name, to_expression_class_name',
            'doc': 'Creates a connection between two material expressions.',
        },
        'create_expression': {
            'params': 'material_path, expression_class_name, node_pos_x=0, node_pos_y=0',
            'doc': 'Creates a new material expression node within the supplied material.',
        },
        'get_mi_scalar_param': {
            'params': 'instance_path, parameter_name',
            'doc': 'Gets the current scalar (float) parameter value from a Material Instance Constant.',
        },
        'get_mi_static_switch': {
            'params': 'instance_path, parameter_name',
            'doc': 'Gets a static switch parameter from a Material Instance. Returns JSON string.',
        },
        'get_mi_texture_param': {
            'params': 'instance_path, parameter_name',
            'doc': 'Gets a texture parameter from a Material Instance. Returns JSON string with texture path.',
        },
        'get_mi_vector_param': {
            'params': 'instance_path, parameter_name',
            'doc': 'Gets a vector parameter from a Material Instance. Returns JSON string.',
        },
        'recompile': {
            'params': 'material_path',
            'doc': "Triggers a recompile of a material or material instance's parent. Saves the asset.",
        },
        'set_mi_scalar_param': {
            'params': 'instance_path, parameter_name, value',
            'doc': 'Sets the scalar (float) parameter value for a Material Instance Constant.',
        },
        'set_mi_static_switch': {
            'params': 'instance_path, parameter_name, value',
            'doc': 'Sets a static switch parameter on a Material Instance. Returns JSON string.',
        },
        'set_mi_texture_param': {
            'params': 'instance_path, parameter_name, texture_path',
            'doc': 'Sets a texture parameter on a Material Instance. Provide texture asset path. Returns JSON string.',
        },
        'set_mi_vector_param': {
            'params': 'instance_path, parameter_name, value',
            'doc': 'Sets a vector parameter on a Material Instance. Expects value as [R,G,B,A]. Returns JSON string.',
        },
    },
    'umg': {
        'add_widget': {
            'params': 'asset_path, widget_type, widget_name, parent_name',
            'doc': '',
        },
        'compile_widget_blueprint': {
            'params': 'asset_path',
            'doc': '',
        },
        'create_widget_blueprint': {
            'params': "name, path, parent_class='UserWidget'",
            'doc': '',
        },
        'get_widget_blueprint_info': {
            'params': 'asset_path',
            'doc': '',
        },
        'get_widget_property': {
            'params': 'asset_path, widget_name, property_name',
            'doc': 'Gets the value of a C++ UPROPERTY on a named widget.',
        },
        'remove_widget': {
            'params': 'asset_path, widget_name',
            'doc': '',
        },
        'set_slot_layout': {
            'params': 'asset_path, widget_name, anchor_min_x=0.5, anchor_min_y=0.5, anchor_max_x=0.5, anchor_max_y=0.5, offset_x=0.0, offset_y=0.0, size_x=100.0, size_y=40.0',
            'doc': 'Sets CanvasPanelSlot layout (anchors + offset + size) on a widget.',
        },
        'set_text_style': {
            'params': 'asset_path, widget_name, font_size=24, color_r=1.0, color_g=1.0, color_b=1.0, color_a=1.0, outline_size=0',
            'doc': 'Sets font size, text color, and outline size on a TextBlock widget.',
        },
        'set_widget_properties': {
            'params': 'asset_path, widget_name, properties',
            'doc': '',
        },
        'set_widget_property': {
            'params': 'asset_path, widget_name, property_name, value',
            'doc': 'Sets a C++ UPROPERTY on a named widget from a string value.',
        },
    },
    'util': {
        'execute_python': {
            'params': 'code',
            'doc': 'Runs arbitrary Unreal Python code. Full API access; fastest path to prototype new actions.',
        },
        'get_output_log': {
            'params': 'line_count=50, keyword',
            'doc': 'Returns recent lines from the Unreal Engine output log file.',
        },
        'livecoding_compile': {
            'params': '',
            'doc': 'Triggers C++ Live Coding and waits for the compile result.',
        },
        'print_message': {
            'params': 'message',
            'doc': 'Logs a message to the Unreal log and returns a JSON success response.',
        },
    },
}
