# Copyright (c) 2025 GenOrca. All Rights Reserved.
#
# AUTO-GENERATED by generate_catalog.py — do not edit by hand.
# Regenerate: python generate_catalog.py

CATALOG = {
    'actor': {
        'add_actor_tag': {
            'params': 'actor_label, tag',
            'doc': 'Adds a tag to an actor (Actor.Tags).',
        },
        'attach_actor': {
            'params': "child_label, parent_label, socket_name=''",
            'doc': 'Attaches one actor to another (keeps world transform). Optional socket on the parent.',
        },
        'delete_by_label': {
            'params': 'actor_label',
            'doc': 'Deletes an actor with the specified name from the current level.',
        },
        'detach_actor': {
            'params': 'actor_label',
            'doc': 'Detaches an actor from its parent (keeps world transform).',
        },
        'duplicate_actor': {
            'params': 'actor_label, offset',
            'doc': 'Duplicates a specific actor (by label) with an optional [x,y,z] offset.',
        },
        'duplicate_selected': {
            'params': 'offset',
            'doc': 'Duplicates all selected actors in the editor and applies a position offset to each duplicate.',
        },
        'get_actor_bounds': {
            'params': 'actor_label',
            'doc': "Returns an actor's world-space bounds (origin + box extent).",
        },
        'get_actor_folder': {
            'params': 'actor_label',
            'doc': 'Returns the World Outliner folder path of an actor.',
        },
        'get_actor_tags': {
            'params': 'actor_label',
            'doc': 'Returns the gameplay tags (Actor.Tags) of an actor.',
        },
        'get_actors_of_class': {
            'params': 'class_path',
            'doc': "Lists labels of level actors of the given class path (e.g. '/Script/Engine.PointLight').",
        },
        'get_all_details': {
            'params': '',
            'doc': 'Lists all actors in the current level with detailed information including',
        },
        'get_attached_actors': {
            'params': 'actor_label',
            'doc': 'Lists the labels of actors attached to the given actor.',
        },
        'get_component_property': {
            'params': 'actor_label, component_name, property_name',
            'doc': 'Reads a property on a named component of a live level actor.',
        },
        'get_in_view_frustum': {
            'params': '',
            'doc': "Retrieves a list of actors that are potentially visible within the active editor viewport's frustum.",
        },
        'get_property': {
            'params': 'actor_label, property_name',
            'doc': 'Gets a property value from an actor using get_editor_property().',
        },
        'get_selected_actors': {
            'params': '',
            'doc': 'Lists the currently selected level actors (label + class).',
        },
        'get_transform': {
            'params': 'actor_label',
            'doc': "Returns an actor's world location, rotation, and scale.",
        },
        'invert_selection': {
            'params': '',
            'doc': 'Inverts the selection of actors in the current level.',
        },
        'line_trace': {
            'params': "ray_start, ray_end, trace_channel='Visibility', actors_to_ignore_labels, trace_complex=True",
            'doc': 'Performs a line trace (raycast) and returns hit information without spawning anything.',
        },
        'list_actor_components': {
            'params': 'actor_label',
            'doc': 'Lists the components on an actor (name + class).',
        },
        'list_all_with_locations': {
            'params': '',
            'doc': 'Lists all actors in the current level along with their world locations.',
        },
        'remove_actor_tag': {
            'params': 'actor_label, tag',
            'doc': 'Removes a tag from an actor (Actor.Tags).',
        },
        'rename_actor': {
            'params': 'actor_label, new_label',
            'doc': 'Renames an actor (changes its World Outliner label).',
        },
        'select_actors': {
            'params': 'actor_labels',
            'doc': 'Selects the given actors by label in the editor (replaces current selection).',
        },
        'select_all': {
            'params': '',
            'doc': 'Selects all actors in the current level.',
        },
        'set_actor_folder': {
            'params': 'actor_label, folder_path',
            'doc': 'Sets the World Outliner folder path of an actor.',
        },
        'set_actor_hidden': {
            'params': 'actor_label, hidden',
            'doc': 'Shows/hides an actor in the editor viewport (temporary editor visibility).',
        },
        'set_component_property': {
            'params': 'actor_label, component_name, property_name, value',
            'doc': "Sets a property on a named component of a live level actor (e.g. PointLightComponent 'intensity').",
        },
        'set_location': {
            'params': 'actor_label, location',
            'doc': '',
        },
        'set_property': {
            'params': 'actor_label, property_name, value',
            'doc': 'Sets a property value on an actor using set_editor_property().',
        },
        'set_rotation': {
            'params': 'actor_label, rotation',
            'doc': '',
        },
        'set_scale': {
            'params': 'actor_label, scale',
            'doc': '',
        },
        'set_transform': {
            'params': 'actor_label, location, rotation, scale',
            'doc': 'Sets the transform (location, rotation, scale) of a specified actor.',
        },
        'spawn_from_class': {
            'params': 'class_path, location, rotation',
            'doc': 'Spawns an actor from the specified class path at the given location and rotation',
        },
        'spawn_from_object': {
            'params': 'asset_path, location',
            'doc': 'Spawns an actor from the specified asset path at the given location.',
        },
        'spawn_on_surface_raycast': {
            'params': "asset_or_class_path, ray_start, ray_end, is_class_path=True, desired_rotation, location_offset, trace_channel='Visibility', actors_to_ignore_labels",
            'doc': '',
        },
    },
    'anim_blueprint': {
        'add_anim_graph_sequence_player': {
            'params': 'asset_path, anim_sequence_path, link_to_output_pose=True',
            'doc': 'Adds a looping Sequence Player to the AnimGraph, optionally wired to the Output Pose.',
        },
        'build_anim_state_machine': {
            'params': 'asset_path, spec',
            'doc': 'Builds an arbitrary AnimGraph state machine from a spec: states[{name,anim?}], entry?, transitions[{from,to,var?,op?,value?}].',
        },
        'create_anim_blueprint': {
            'params': "asset_path, skeleton_path, parent_class_path='/Script/Engine.AnimInstance'",
            'doc': 'Creates an Animation Blueprint bound to a Skeleton (parent defaults to AnimInstance).',
        },
        'get_anim_blueprint_info': {
            'params': 'asset_path',
            'doc': "Returns an AnimBlueprint's target skeleton, generated class, and graph names.",
        },
    },
    'animation': {
        'add_float_curve': {
            'params': 'asset_path, curve_name, time_seconds, value',
            'doc': 'Adds a float curve to an AnimSequence, optionally with an initial key at time_seconds=value.',
        },
        'add_notify_track': {
            'params': 'asset_path, track_name',
            'doc': 'Adds a notify track to an AnimSequence.',
        },
        'add_socket': {
            'params': 'asset_path, socket_name, bone_name, location, rotation',
            'doc': 'Adds a socket on a bone of a SkeletalMesh. location=[x,y,z], rotation=[pitch,yaw,roll].',
        },
        'add_sync_marker': {
            'params': 'asset_path, track_name, marker_name, time_seconds',
            'doc': 'Adds a sync marker at a time (seconds) on a notify track. Creates the track if needed.',
        },
        'find_socket': {
            'params': 'asset_path, socket_name',
            'doc': 'Returns details of a named socket on a SkeletalMesh, or success=False if not found.',
        },
        'get_anim_sequence_info': {
            'params': 'asset_path',
            'doc': 'Returns length, frame count, approximate fps, and skeleton path of an AnimSequence.',
        },
        'get_skeletal_mesh_info': {
            'params': 'asset_path',
            'doc': 'Returns the skeleton path, socket count, and material-slot count of a SkeletalMesh.',
        },
        'get_skeleton_info': {
            'params': 'asset_path',
            'doc': 'Returns curve metadata names for a Skeleton asset.',
        },
        'list_bones': {
            'params': 'asset_path',
            'doc': 'Lists reference-skeleton bones (name, index, parent) of a SkeletalMesh.',
        },
        'list_curves': {
            'params': 'asset_path',
            'doc': 'Lists float animation curve names on an AnimSequence.',
        },
        'list_notifies': {
            'params': 'asset_path',
            'doc': 'Lists notify event names on an AnimSequence.',
        },
        'list_notify_tracks': {
            'params': 'asset_path',
            'doc': 'Lists the notify track names on an AnimSequence.',
        },
        'list_sockets': {
            'params': 'asset_path',
            'doc': 'Lists sockets on a SkeletalMesh (name, bone, relative location/rotation).',
        },
        'list_sync_markers': {
            'params': 'asset_path',
            'doc': 'Lists sync markers (name + time) on an AnimSequence.',
        },
        'remove_curve': {
            'params': 'asset_path, curve_name',
            'doc': 'Removes a float curve from an AnimSequence.',
        },
        'remove_notify_track': {
            'params': 'asset_path, track_name',
            'doc': 'Removes a notify track (and its notifies) from an AnimSequence.',
        },
        'remove_socket': {
            'params': 'asset_path, socket_name',
            'doc': 'Removes a named socket from a SkeletalMesh.',
        },
    },
    'asset': {
        'asset_exists': {
            'params': 'asset_path',
            'doc': 'Returns whether an asset exists at the given path.',
        },
        'delete_asset': {
            'params': 'asset_path',
            'doc': 'Deletes an asset from the content browser.',
        },
        'delete_directory': {
            'params': 'directory_path',
            'doc': 'Deletes a content-browser directory and its assets.',
        },
        'duplicate_asset': {
            'params': 'source_path, dest_path',
            'doc': 'Duplicates an asset to a new content-browser path.',
        },
        'export_fbx': {
            'params': 'asset_path, file_path',
            'doc': 'Exports a StaticMesh, SkeletalMesh, or AnimSequence asset to an FBX file.',
        },
        'find_by_query': {
            'params': 'name, asset_type',
            'doc': "Returns a JSON list of asset paths under '/Game' matching the given query dict.",
        },
        'find_referencers': {
            'params': 'asset_path',
            'doc': 'Lists packages that reference the given asset.',
        },
        'get_asset_info': {
            'params': 'asset_path',
            'doc': 'Returns class and package info for an asset.',
        },
        'get_dependencies': {
            'params': 'asset_path',
            'doc': 'Lists packages that the given asset depends on (references).',
        },
        'get_gltf_import_status': {
            'params': 'destination_path',
            'doc': 'Polls a scheduled glTF import; returns done + imported assets once Interchange finishes.',
        },
        'get_metadata_tag': {
            'params': 'asset_path, tag',
            'doc': 'Reads a metadata tag value on an asset (empty string if unset).',
        },
        'get_static_mesh_details': {
            'params': 'asset_path',
            'doc': 'Retrieves the bounding box and dimensions of a static mesh asset.',
        },
        'import_fbx': {
            'params': "file_path, destination_path, destination_name='', as_skeletal=False, import_materials=False, import_textures=False, import_animations=False",
            'doc': 'Imports an FBX file as a Static/Skeletal mesh using the legacy FBX importer.',
        },
        'import_gltf': {
            'params': 'file_path, destination_path',
            'doc': 'Imports a .glb/.gltf via Interchange, deferred to the editor tick. Poll get_gltf_import_status for the result.',
        },
        'import_texture': {
            'params': "file_path, destination_path, destination_name=''",
            'doc': 'Imports an image file (PNG/JPG/TGA...) as a Texture2D using the legacy texture importer.',
        },
        'list_assets': {
            'params': 'directory_path, recursive=True',
            'doc': 'Lists asset paths under a content directory.',
        },
        'make_directory': {
            'params': 'directory_path',
            'doc': 'Creates a content-browser directory.',
        },
        'remove_metadata_tag': {
            'params': 'asset_path, tag',
            'doc': 'Removes a metadata tag from an asset.',
        },
        'rename_asset': {
            'params': 'source_path, dest_path',
            'doc': 'Renames/moves an asset to a new content-browser path.',
        },
        'save_asset': {
            'params': 'asset_path',
            'doc': 'Saves an asset to disk.',
        },
        'set_metadata_tag': {
            'params': 'asset_path, tag, value',
            'doc': 'Sets a metadata tag value on an asset.',
        },
    },
    'behavior_tree': {
        'add_blackboard_key': {
            'params': 'asset_path, key_name, key_type, instance_synced=False',
            'doc': 'Adds a new key to a Blackboard asset.',
        },
        'build_behavior_tree': {
            'params': 'asset_path, tree_structure',
            'doc': 'Builds a complete Behavior Tree from a JSON structure.',
        },
        'create_behavior_tree': {
            'params': 'asset_path, blackboard_path',
            'doc': 'Creates a new empty Behavior Tree asset.',
        },
        'create_blackboard': {
            'params': 'asset_path, parent_path',
            'doc': 'Creates a new Blackboard Data asset.',
        },
        'get_behavior_tree_structure': {
            'params': 'asset_path',
            'doc': 'Returns the full tree structure of a Behavior Tree asset as JSON.',
        },
        'get_blackboard_data': {
            'params': 'asset_path',
            'doc': 'Reads all keys from a Blackboard asset.',
        },
        'get_bt_node_details': {
            'params': 'asset_path, node_name',
            'doc': 'Retrieves detailed properties of a specific node in a Behavior Tree.',
        },
        'get_selected_bt_nodes': {
            'params': '',
            'doc': 'Returns details of selected nodes in the currently open BT editor.',
        },
        'list_behavior_trees': {
            'params': '',
            'doc': 'Lists all Behavior Tree assets under /Game.',
        },
        'list_bt_node_classes': {
            'params': '',
            'doc': 'Lists all available BT node classes (composites, tasks, decorators, services).',
        },
        'remove_blackboard_key': {
            'params': 'asset_path, key_name',
            'doc': 'Removes a key from a Blackboard asset.',
        },
        'set_blackboard_to_behavior_tree': {
            'params': 'bt_path, bb_path',
            'doc': 'Links a Blackboard asset to a Behavior Tree.',
        },
    },
    'blueprint': {
        'add_blueprint_node': {
            'params': "asset_path, graph_name='EventGraph', node_json",
            'doc': 'Adds a single node to a Blueprint graph.',
        },
        'add_component_to_blueprint': {
            'params': "asset_path, component_class_path, component_name, location_x=0.0, location_y=0.0, location_z=0.0, rotation_pitch=0.0, rotation_yaw=0.0, rotation_roll=0.0, parent_component_name=''",
            'doc': "Adds a component to a Blueprint's SCS.",
        },
        'add_variable': {
            'params': "asset_path, variable_name, variable_type='real'",
            'doc': 'Adds a member variable to a Blueprint. variable_type: int, byte, bool, real (float), name, string, text.',
        },
        'auto_layout_graph': {
            'params': "asset_path, graph_name='EventGraph', x_step=380.0, y_step=200.0",
            'doc': 'Auto-lays out all nodes in a Blueprint graph using DAG topological sort.',
        },
        'build_blueprint_graph': {
            'params': "asset_path, graph_name='EventGraph', graph_structure",
            'doc': 'Builds a Blueprint graph from JSON adjacency list.',
        },
        'compile_blueprint': {
            'params': 'asset_path',
            'doc': 'Compiles a Blueprint and returns the result.',
        },
        'connect_blueprint_pins': {
            'params': "asset_path, graph_name='EventGraph', source_node, source_pin, target_node, target_pin",
            'doc': 'Connects two pins in a Blueprint graph.',
        },
        'create_blueprint': {
            'params': "asset_path, parent_class_path='/Script/Engine.Actor'",
            'doc': 'Creates a Blueprint asset with the given parent class (default Actor).',
        },
        'get_blueprint_graph_info': {
            'params': "asset_path, graph_name='EventGraph'",
            'doc': 'Returns the full graph info for a Blueprint graph.',
        },
        'get_selected_bp_node_infos': {
            'params': '',
            'doc': 'Returns compact blueprint node info optimized for LLM token efficiency.',
        },
        'get_selected_bp_nodes': {
            'params': '',
            'doc': 'Returns information about currently selected blueprint nodes in the editor.',
        },
        'list_blueprint_components': {
            'params': 'asset_path',
            'doc': 'Lists all SCS components on a Blueprint.',
        },
        'list_blueprint_variables': {
            'params': 'asset_path',
            'doc': 'Lists all variables defined in a Blueprint.',
        },
        'list_callable_functions': {
            'params': "asset_path, filter=''",
            'doc': 'Lists callable functions available in a Blueprint context.',
        },
        'remove_blueprint_node': {
            'params': "asset_path, graph_name='EventGraph', node_name",
            'doc': 'Removes a node from a Blueprint graph.',
        },
        'remove_component_from_blueprint': {
            'params': 'asset_path, component_name',
            'doc': "Removes a component by variable name from a Blueprint's SCS.",
        },
        'set_blueprint_node_position': {
            'params': "asset_path, graph_name='EventGraph', node_name, pos_x=0.0, pos_y=0.0",
            'doc': 'Sets the canvas position of a node in a Blueprint graph.',
        },
        'set_component_property': {
            'params': 'asset_path, component_name, property_name, value',
            'doc': "Sets a property on a component template in a Blueprint's SCS.",
        },
        'set_variable_flags': {
            'params': 'asset_path, variable_name, instance_editable, expose_on_spawn',
            'doc': "Sets a Blueprint variable's 'Instance Editable' and/or 'Expose On Spawn' flags.",
        },
    },
    'control_rig': {
        'add_rig_bone': {
            'params': "asset_path, bone_name, parent_name='', parent_type='bone', location",
            'doc': 'Adds a bone to a Control Rig hierarchy under an optional parent (requires the ControlRig plugin).',
        },
        'add_rig_null': {
            'params': "asset_path, null_name, parent_name='', parent_type='bone', location",
            'doc': 'Adds a null (group transform) to a Control Rig hierarchy (requires the ControlRig plugin).',
        },
        'add_unit_node': {
            'params': "asset_path, struct_path, method='Execute', pos_x=0.0, pos_y=0.0",
            'doc': "Adds a RigVM unit node by struct path (e.g. '/Script/ControlRig.RigUnit_GetTransform') to a Control Rig graph (requires the ControlRig plugin).",
        },
        'create_control_rig': {
            'params': 'asset_path, skeletal_mesh_path',
            'doc': 'Creates a Control Rig at asset_path; with a skeletal mesh, imports its bones and sets it as preview (requires the ControlRig plugin).',
        },
        'get_control_rig_info': {
            'params': 'asset_path',
            'doc': 'Returns element counts by type and the preview mesh of a Control Rig (requires the ControlRig plugin).',
        },
        'recompile_control_rig': {
            'params': 'asset_path',
            'doc': "Recompiles a Control Rig's VM and saves it (requires the ControlRig plugin).",
        },
    },
    'data_table': {
        'create_data_table': {
            'params': 'asset_path, row_struct_path',
            'doc': "Creates a DataTable asset with the given row struct (e.g. '/Script/MyModule.MyRow' or a UserDefinedStruct path).",
        },
        'does_row_exist': {
            'params': 'asset_path, row_name',
            'doc': 'Returns whether a row exists in a DataTable.',
        },
        'export_to_csv': {
            'params': 'asset_path',
            'doc': 'Returns all rows of a DataTable as a CSV string.',
        },
        'get_column_names': {
            'params': 'asset_path',
            'doc': "Lists the column (property) names of a DataTable's row struct.",
        },
        'get_row_names': {
            'params': 'asset_path',
            'doc': 'Lists the row names of a DataTable.',
        },
        'get_rows_as_json': {
            'params': 'asset_path',
            'doc': "Returns all rows of a DataTable as a JSON string (under the 'rows' field).",
        },
        'remove_row': {
            'params': 'asset_path, row_name',
            'doc': 'Removes a row from a DataTable by name.',
        },
        'set_rows_from_json': {
            'params': 'asset_path, json_string',
            'doc': "Replaces a DataTable's rows from a JSON string (array of row objects with a 'Name' key).",
        },
    },
    'editor': {
        'close_asset_editor': {
            'params': 'asset_path',
            'doc': 'Closes any open editor for the given asset.',
        },
        'create_proxy_actor': {
            'params': 'actor_labels, base_package_name, screen_size=300, destroy_source_actors=False',
            'doc': 'Bakes static mesh actors into ONE simplified proxy mesh (Proxy Geometry tool) and spawns it.',
        },
        'get_open_assets': {
            'params': '',
            'doc': 'Lists assets that currently have an editor open.',
        },
        'get_selected_assets': {
            'params': '',
            'doc': 'Gets the set of currently selected assets.',
        },
        'join_actors': {
            'params': "actor_labels, new_actor_label=''",
            'doc': 'Joins static mesh actors into one actor with multiple components (no new mesh asset is baked).',
        },
        'merge_actors': {
            'params': 'actor_labels, base_package_name, destroy_source_actors=False',
            'doc': 'Merges static mesh actors into ONE new static mesh asset + actor (geometry is baked together).',
        },
        'open_editor_for_asset': {
            'params': 'asset_path',
            'doc': 'Opens the asset-specific editor (Blueprint, Material, etc.) for an asset.',
        },
        'replace_mesh_on_selected': {
            'params': 'mesh_to_be_replaced_path, new_mesh_path',
            'doc': "Replaces static meshes on components of selected actors using Unreal's batch API if available.",
        },
        'replace_mesh_on_specified': {
            'params': 'actor_paths, mesh_to_be_replaced_path, new_mesh_path',
            'doc': "Replaces static meshes on components of specified actors using Unreal's batch API if available.",
        },
        'replace_mtl_on_selected': {
            'params': 'material_to_be_replaced_path, new_material_path',
            'doc': '',
        },
        'replace_mtl_on_specified': {
            'params': 'actor_paths, material_to_be_replaced_path, new_material_path',
            'doc': '',
        },
        'replace_selected_with_bp': {
            'params': 'blueprint_asset_path',
            'doc': "Replaces the currently selected actors with new actors spawned from a specified Blueprint asset path using Unreal's official API.",
        },
    },
    'game': {
        'add_input_action': {
            'params': "asset_path, value_type='Bool'",
            'doc': 'Creates a new Enhanced Input Action asset.',
        },
        'add_input_mapping': {
            'params': 'mapping_context_path, action_path, key_name',
            'doc': 'Creates/updates an InputMappingContext with a key-to-action mapping.',
        },
        'set_game_mode': {
            'params': 'game_mode_class_path',
            'doc': "Sets the GameMode Override on the current level's World Settings.",
        },
    },
    'gas': {
        'add_effect_modifier': {
            'params': "asset_path, attribute_set_path, attribute_name, op='add_base', magnitude=1.0",
            'doc': 'Appends an attribute modifier (e.g. Health add_base +25) to a GameplayEffect. attribute_set_path is the AttributeSet class path (requires the GameplayAbilities plugin).',
        },
        'add_gameplay_tag': {
            'params': "tag, comment=''",
            'doc': 'Registers a gameplay tag in Config/DefaultGameplayTags.ini — takes effect after an editor restart (requires the GameplayAbilities plugin).',
        },
        'clear_effect_modifiers': {
            'params': 'asset_path',
            'doc': 'Removes all modifiers from a GameplayEffect blueprint (requires the GameplayAbilities plugin).',
        },
        'create_ability_blueprint': {
            'params': 'asset_path, parent_class_path',
            'doc': 'Creates a GameplayAbility blueprint; parent_class_path may point at a custom GA subclass (requires the GameplayAbilities plugin).',
        },
        'create_effect_blueprint': {
            'params': "asset_path, duration_policy='instant', duration_seconds",
            'doc': 'Creates a GameplayEffect blueprint with a duration policy: instant, has_duration (+seconds), or infinite (requires the GameplayAbilities plugin).',
        },
        'get_ability_info': {
            'params': 'asset_path',
            'doc': 'Returns parent class, ability tags, and cost/cooldown effect classes of a GameplayAbility blueprint (requires the GameplayAbilities plugin).',
        },
        'get_effect_info': {
            'params': 'asset_path',
            'doc': 'Returns duration policy/seconds and decoded modifiers of a GameplayEffect blueprint (requires the GameplayAbilities plugin).',
        },
        'list_gameplay_tags': {
            'params': "prefix=''",
            'doc': 'Lists gameplay tags registered in Config/DefaultGameplayTags.ini, optionally filtered by prefix (requires the GameplayAbilities plugin).',
        },
        'set_ability_costs': {
            'params': 'asset_path, cost_effect_path, cooldown_effect_path',
            'doc': 'Wires cost and/or cooldown GameplayEffect blueprints onto a GameplayAbility (requires the GameplayAbilities plugin).',
        },
        'set_ability_tags': {
            'params': 'asset_path, tags',
            'doc': 'Sets the AbilityTags container on a GameplayAbility; unregistered tags are reported, not silently dropped (requires the GameplayAbilities plugin).',
        },
        'set_effect_duration': {
            'params': 'asset_path, duration_policy, duration_seconds',
            'doc': "Changes a GameplayEffect's duration policy (instant / has_duration+seconds / infinite) (requires the GameplayAbilities plugin).",
        },
    },
    'layer': {
        'add_actor_to_layer': {
            'params': 'actor_label, layer_name',
            'doc': 'Adds an actor to a layer (creates the layer if needed).',
        },
        'create_layer': {
            'params': 'layer_name',
            'doc': 'Creates a new (empty) layer.',
        },
        'delete_layer': {
            'params': 'layer_name',
            'doc': 'Deletes a layer.',
        },
        'get_actors_in_layer': {
            'params': 'layer_name',
            'doc': 'Lists the labels of actors assigned to a layer.',
        },
        'list_layers': {
            'params': '',
            'doc': 'Lists all layer names in the current world.',
        },
        'remove_actor_from_layer': {
            'params': 'actor_label, layer_name',
            'doc': 'Removes an actor from a layer.',
        },
    },
    'level': {
        'create_level': {
            'params': 'level_path',
            'doc': 'Creates a new empty level and saves it at the given content-browser path.',
        },
        'get_current_level_path': {
            'params': '',
            'doc': 'Returns the path of the currently open editor world/level.',
        },
        'list_level_actors': {
            'params': 'class_filter',
            'doc': 'Lists all actors in the current level.',
        },
        'load_level': {
            'params': 'level_path',
            'doc': 'Opens (loads) an existing level in the editor.',
        },
        'save_all_levels': {
            'params': '',
            'doc': 'Saves all dirty levels.',
        },
        'save_current_level': {
            'params': '',
            'doc': 'Saves the currently open level. Returns success=False for an unsaved/untitled level.',
        },
        'set_world_settings': {
            'params': 'gravity, time_dilation',
            'doc': 'Modifies WorldSettings of the current level.',
        },
    },
    'level_sequence': {
        'add_anim_track': {
            'params': 'asset_path, binding_name, anim_path, start_seconds, end_seconds',
            'doc': 'Adds a skeletal-animation track playing anim_path on a binding (defaults to the playback range).',
        },
        'add_camera': {
            'params': 'asset_path, spawnable=True',
            'doc': 'Adds a CineCamera to a Level Sequence with a Camera Cut track bound to it (official create_camera path).',
        },
        'add_possessable': {
            'params': 'asset_path, actor_label',
            'doc': 'Adds a possessable binding for an existing level actor (by World Outliner label). Returns the binding name.',
        },
        'add_spawnable_from_class': {
            'params': 'asset_path, class_path',
            'doc': "Adds a spawnable binding from a class path (e.g. '/Script/CinematicCamera.CineCameraActor'). Returns the binding name.",
        },
        'add_transform_keyframe': {
            'params': 'asset_path, binding_name, time_seconds, location, rotation, scale',
            'doc': "Adds a keyframe at time_seconds on a binding's transform track. Provide any of",
        },
        'add_transform_track': {
            'params': 'asset_path, binding_name',
            'doc': 'Adds a 3D transform track (with one section) to a binding.',
        },
        'close_sequencer': {
            'params': '',
            'doc': 'Closes the Sequencer editor if one is open.',
        },
        'convert_binding': {
            'params': "asset_path, binding_name, to='spawnable'",
            'doc': "Converts a binding between possessable and spawnable. to='spawnable' or 'possessable'.",
        },
        'create_level_sequence': {
            'params': 'asset_path, fps=30.0, duration_seconds=5.0',
            'doc': 'Creates a Level Sequence asset with the given frame rate and playback duration.',
        },
        'get_sequence_info': {
            'params': 'asset_path',
            'doc': 'Returns frame rate, playback range (seconds), and the bindings of a Level Sequence.',
        },
        'open_in_sequencer': {
            'params': 'asset_path',
            'doc': 'Opens a Level Sequence in the Sequencer editor (and focuses it).',
        },
        'remove_binding': {
            'params': 'asset_path, binding_name',
            'doc': 'Removes a binding (spawnable or possessable) from a Level Sequence by name.',
        },
        'set_playback_range': {
            'params': 'asset_path, start_seconds, end_seconds',
            'doc': 'Sets the playback range (in seconds) of a Level Sequence.',
        },
    },
    'material': {
        'connect_expressions': {
            'params': 'material_path, from_expression_identifier, from_output_name, to_expression_identifier, to_input_name, from_expression_class_name, to_expression_class_name',
            'doc': 'Creates a connection between two material expressions.',
        },
        'connect_property': {
            'params': "material_path, from_expression_identifier, from_output_name='', property_name, from_expression_class_name",
            'doc': 'Connects an expression output to a material property (e.g. BaseColor, Metallic, Roughness, Normal).',
        },
        'create_expression': {
            'params': 'material_path, expression_class_name, node_pos_x=0, node_pos_y=0',
            'doc': 'Creates a new material expression node within the supplied material.',
        },
        'create_material': {
            'params': 'material_path',
            'doc': 'Creates a new Material asset at the given content-browser path.',
        },
        'create_material_instance': {
            'params': 'instance_path, parent_path',
            'doc': 'Creates a Material Instance Constant, optionally parented to parent_path.',
        },
        'delete_expression': {
            'params': 'material_path, expression_identifier, expression_class_name',
            'doc': 'Deletes a material expression node identified by name/desc/type.',
        },
        'get_material_info': {
            'params': 'material_path',
            'doc': 'Returns expression count and a list of expressions (name, class, position) for a material.',
        },
        'get_mi_scalar_param': {
            'params': 'instance_path, parameter_name',
            'doc': 'Gets the current scalar (float) parameter value from a Material Instance Constant.',
        },
        'get_mi_static_switch': {
            'params': 'instance_path, parameter_name',
            'doc': 'Gets a static switch parameter from a Material Instance. Returns JSON string.',
        },
        'get_mi_texture_param': {
            'params': 'instance_path, parameter_name',
            'doc': 'Gets a texture parameter from a Material Instance. Returns JSON string with texture path.',
        },
        'get_mi_vector_param': {
            'params': 'instance_path, parameter_name',
            'doc': 'Gets a vector parameter from a Material Instance. Returns JSON string.',
        },
        'layout_expressions': {
            'params': 'material_path',
            'doc': 'Auto-lays out all expression nodes in a material graph.',
        },
        'list_parameters': {
            'params': 'material_path',
            'doc': 'Lists scalar / vector / texture / static-switch parameter names for a material or material instance.',
        },
        'recompile': {
            'params': 'material_path',
            'doc': "Triggers a recompile of a material or material instance's parent. Saves the asset.",
        },
        'set_expression_property': {
            'params': 'material_path, expression_identifier, property_name, value, expression_class_name',
            'doc': "Sets an editor property on a material expression (e.g. 'r' on a Constant,",
        },
        'set_instance_parent': {
            'params': 'instance_path, parent_path',
            'doc': 'Reparents a Material Instance Constant to a new parent material/instance.',
        },
        'set_mi_scalar_param': {
            'params': 'instance_path, parameter_name, value',
            'doc': 'Sets the scalar (float) parameter value for a Material Instance Constant.',
        },
        'set_mi_static_switch': {
            'params': 'instance_path, parameter_name, value',
            'doc': 'Sets a static switch parameter on a Material Instance. Returns JSON string.',
        },
        'set_mi_texture_param': {
            'params': 'instance_path, parameter_name, texture_path',
            'doc': 'Sets a texture parameter on a Material Instance. Provide texture asset path. Returns JSON string.',
        },
        'set_mi_vector_param': {
            'params': 'instance_path, parameter_name, value',
            'doc': 'Sets a vector parameter on a Material Instance. Expects value as [R,G,B,A]. Returns JSON string.',
        },
    },
    'retarget': {
        'add_retarget_chain': {
            'params': "ik_rig_path, chain_name, start_bone, end_bone, goal_name=''",
            'doc': "Adds a retarget chain (e.g. 'Spine': spine_01..spine_03) to an IK Rig (requires the IKRig plugin).",
        },
        'auto_map_chains': {
            'params': "retargeter_path, mode='FUZZY', force=True",
            'doc': 'Re-runs chain mapping on an IK Retargeter. mode: FUZZY, EXACT, or CLEAR (requires the IKRig plugin).',
        },
        'batch_retarget': {
            'params': "retargeter_path, anim_paths, source_mesh_path, target_mesh_path, search='', replace='', prefix='', suffix='_Retargeted'",
            'doc': 'Duplicates and retargets animations through an IK Retargeter; returns the new asset paths (requires the IKRig plugin).',
        },
        'create_ik_rig': {
            'params': 'asset_path, skeletal_mesh_path, retarget_root',
            'doc': 'Creates an IK Rig for a skeletal mesh, optionally setting the retarget root bone (requires the IKRig plugin).',
        },
        'create_retargeter': {
            'params': 'asset_path, source_ik_rig_path, target_ik_rig_path, auto_map=True',
            'doc': 'Creates an IK Retargeter wired to source/target IK Rigs, with optional fuzzy chain auto-mapping (requires the IKRig plugin).',
        },
        'get_ik_rig_info': {
            'params': 'ik_rig_path',
            'doc': 'Returns the skeletal mesh, retarget root, and chains of an IK Rig (requires the IKRig plugin).',
        },
    },
    'static_mesh': {
        'add_simple_collision': {
            'params': "asset_path, shape='BOX'",
            'doc': 'Adds a simple collision primitive to a StaticMesh. shape: BOX, SPHERE, CAPSULE, NDOP10_X/Y/Z, NDOP18, NDOP26.',
        },
        'get_collision_info': {
            'params': 'asset_path',
            'doc': 'Returns collision complexity and simple/convex collision counts of a StaticMesh.',
        },
        'get_lod_screen_sizes': {
            'params': 'asset_path',
            'doc': 'Returns the screen-size threshold of each LOD on a StaticMesh.',
        },
        'get_static_mesh_info': {
            'params': 'asset_path',
            'doc': 'Returns LOD/section/triangle/vertex/material counts and Nanite state of a StaticMesh.',
        },
        'list_static_mesh_materials': {
            'params': 'asset_path',
            'doc': 'Lists the material slots of a StaticMesh (slot index + material path).',
        },
        'remove_collisions': {
            'params': 'asset_path',
            'doc': 'Removes all simple/convex collision from a StaticMesh.',
        },
        'remove_lods': {
            'params': 'asset_path',
            'doc': 'Removes all LODs except LOD 0 from a StaticMesh.',
        },
        'set_convex_collision': {
            'params': 'asset_path, hull_count=4, max_hull_verts=16, hull_precision=100000',
            'doc': 'Replaces simple collision with auto-generated convex decomposition collision.',
        },
        'set_lod_for_collision': {
            'params': 'asset_path, lod_index',
            'doc': "Sets which LOD's geometry is used for complex collision on a StaticMesh.",
        },
        'set_lod_from_static_mesh': {
            'params': 'asset_path, lod_index, source_path, source_lod_index=0, reuse_existing_material_slots=True',
            'doc': "Adds/sets a LOD on a StaticMesh using geometry from another StaticMesh's LOD.",
        },
        'set_lods': {
            'params': 'asset_path, lod_settings, auto_compute_screen_size=False',
            'doc': 'Generates LODs from reduction settings: lod_settings=[{percent_triangles, screen_size}, ...] (LOD0 first).',
        },
        'set_static_mesh_material': {
            'params': 'asset_path, slot_index, material_path',
            'doc': 'Assigns a material to a StaticMesh material slot.',
        },
    },
    'texture': {
        'get_texture_info': {
            'params': 'asset_path',
            'doc': 'Returns size, memory, sRGB, and compression settings of a Texture2D.',
        },
        'set_texture_compression': {
            'params': 'asset_path, compression',
            'doc': "Sets the compression settings of a Texture2D (e.g. 'TC_DEFAULT', 'TC_NORMALMAP', 'TC_MASKS', 'TC_GRAYSCALE').",
        },
        'set_texture_srgb': {
            'params': 'asset_path, srgb',
            'doc': 'Sets the sRGB flag on a Texture2D.',
        },
    },
    'umg': {
        'add_widget': {
            'params': 'asset_path, widget_type, widget_name, parent_name',
            'doc': '',
        },
        'bind_widget_event': {
            'params': 'asset_path, widget_name, event_name',
            'doc': "Creates a bound event node in the widget BP's event graph for a widget delegate (e.g. Button OnClicked).",
        },
        'compile_widget_blueprint': {
            'params': 'asset_path',
            'doc': '',
        },
        'create_widget_blueprint': {
            'params': "name, path, parent_class='UserWidget'",
            'doc': '',
        },
        'get_widget_blueprint_info': {
            'params': 'asset_path',
            'doc': '',
        },
        'get_widget_property': {
            'params': 'asset_path, widget_name, property_name',
            'doc': 'Gets the value of a C++ UPROPERTY on a named widget.',
        },
        'list_widget_events': {
            'params': 'asset_path, widget_name',
            'doc': 'Lists the bindable multicast-delegate events on a widget (e.g. OnClicked, OnHovered).',
        },
        'remove_widget': {
            'params': 'asset_path, widget_name',
            'doc': '',
        },
        'reparent_widget': {
            'params': 'asset_path, widget_name, new_parent_name',
            'doc': 'Moves a widget under a different panel parent (cycle-guarded).',
        },
        'replace_widget': {
            'params': 'asset_path, widget_name, new_type, new_name',
            'doc': 'Replaces a widget with a new widget of new_type at the same slot (old subtree discarded).',
        },
        'set_slot_layout': {
            'params': 'asset_path, widget_name, anchor_min_x=0.5, anchor_min_y=0.5, anchor_max_x=0.5, anchor_max_y=0.5, offset_x=0.0, offset_y=0.0, size_x=100.0, size_y=40.0',
            'doc': 'Sets CanvasPanelSlot layout (anchors + offset + size) on a widget.',
        },
        'set_text_style': {
            'params': 'asset_path, widget_name, font_size=24, color_r=1.0, color_g=1.0, color_b=1.0, color_a=1.0, outline_size=0',
            'doc': 'Sets font size, text color, and outline size on a TextBlock widget.',
        },
        'set_widget_properties': {
            'params': 'asset_path, widget_name, properties',
            'doc': '',
        },
        'set_widget_property': {
            'params': 'asset_path, widget_name, property_name, value',
            'doc': 'Sets a C++ UPROPERTY on a named widget from a string value.',
        },
        'wrap_widget': {
            'params': 'asset_path, widget_name, wrapper_type, wrapper_name',
            'doc': "Wraps a widget in a new panel (wrapper_type, e.g. 'VerticalBox') that takes its place.",
        },
    },
    'util': {
        'execute_console_command': {
            'params': 'command',
            'doc': "Executes an editor console command (e.g. 'stat fps', 'r.ScreenPercentage 50').",
        },
        'execute_python': {
            'params': 'code',
            'doc': 'Runs arbitrary Unreal Python code. Full API access; fastest path to prototype new actions.',
        },
        'get_cvar': {
            'params': 'name',
            'doc': "Reads the current value of a console variable (CVar) as a string, e.g. 'r.ScreenPercentage'.",
        },
        'get_output_log': {
            'params': 'line_count=50, keyword, context_lines=0',
            'doc': 'Returns recent lines from the UE output log file; optional keyword filter with context_lines around each match.',
        },
        'get_project_info': {
            'params': '',
            'doc': 'Returns project name, directories, and engine version.',
        },
        'get_viewport_camera': {
            'params': '',
            'doc': 'Returns the level viewport camera location and rotation.',
        },
        'is_in_pie': {
            'params': '',
            'doc': 'Returns whether Play-In-Editor is currently active.',
        },
        'list_class_properties': {
            'params': 'class_path',
            'doc': 'Lists the editor-settable property names of a UClass (for discovering what set_property accepts).',
        },
        'list_enum_values': {
            'params': 'enum_name',
            'doc': "Lists the values of an Unreal enum by name (e.g. 'TextureCompressionSettings', 'CollisionTraceFlag').",
        },
        'livecoding_compile': {
            'params': '',
            'doc': 'Triggers C++ Live Coding and waits for the compile result.',
        },
        'print_message': {
            'params': 'message',
            'doc': 'Logs a message to the Unreal log and returns a JSON success response.',
        },
        'save_all_dirty': {
            'params': '',
            'doc': 'Saves all dirty packages (modified maps and content).',
        },
        'screen_to_world': {
            'params': 'x, y, distance=1000.0',
            'doc': "Deprojects a viewport pixel (x, y) to a world location at 'distance' along the view ray.",
        },
        'set_cvar': {
            'params': 'name, value',
            'doc': "Sets a console variable, e.g. name='r.ScreenPercentage', value='75'. Reads it back to confirm.",
        },
        'set_log_verbosity': {
            'params': 'category, verbosity',
            'doc': "Sets a log category's verbosity via the 'Log' console command (e.g. 'LogBlueprint', 'Verbose').",
        },
        'set_viewport_camera': {
            'params': 'location, rotation',
            'doc': 'Sets the level viewport camera. location=[x,y,z], rotation=[pitch,yaw,roll].',
        },
        'start_pie': {
            'params': '',
            'doc': 'Starts Play-In-Editor (asynchronous; begins on the next frame).',
        },
        'stop_pie': {
            'params': '',
            'doc': 'Stops Play-In-Editor.',
        },
        'world_to_screen': {
            'params': 'location',
            'doc': 'Projects a world location to active level-viewport pixel coords (editor viewport, no PIE needed).',
        },
    },
    'vision': {
        'capture_actors': {
            'params': 'actor_labels, width=1280, height=720, fov=60.0, padding=1.6, annotate=True',
            'doc': 'Frames the given actors (by label) from an elevated 3/4 view and captures them.',
        },
        'capture_from': {
            'params': 'location, rotation, width=1280, height=720, fov=90.0',
            'doc': 'Captures the scene from an explicit camera pose. location=[x,y,z], rotation=[pitch,yaw,roll].',
        },
        'capture_viewport': {
            'params': 'width=1280, height=720, fov=90.0',
            'doc': "Captures the active level viewport (3D scene only) as a PNG, returned base64 in 'image_data'.",
        },
    },
}
